### ISSUE TITLE
Log rotation cause panic / SIGSEGV

### ISSUE THREAD

**Issue by CorentinB** [internetarchive/Zeno#70]
This happened on 2 distinct very different crawls, after a LONG time of simply hanging (no crawling, no log, for >1h).

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x125056e]

goroutine 82 [running]:
github.com/internetarchive/Zeno/internal/pkg/log.(*Logfile).Filename(0x0)
        /home/corentin/projects/Zeno/internal/pkg/log/file.go:51 +0x4e
github.com/internetarchive/Zeno/internal/pkg/log.(*fileHandler).Rotate(0xc000129ce0)
        /home/corentin/projects/Zeno/internal/pkg/log/file.go:30 +0x45
github.com/internetarchive/Zeno/internal/pkg/log.(*Logger).rotate(0xc000260e10)
        /home/corentin/projects/Zeno/internal/pkg/log/rotate.go:57 +0x17c
github.com/internetarchive/Zeno/internal/pkg/log.(*Logger).startRotation.func1()
        /home/corentin/projects/Zeno/internal/pkg/log/rotate.go:22 +0x25
created by github.com/internetarchive/Zeno/internal/pkg/log.(*Logger).startRotation in goroutine 1
        /home/corentin/projects/Zeno/internal/pkg/log/rotate.go:17 +0x85
```

**Comment by equals215** [comment]
on it

**Comment by equals215** [comment]
PR ready for review
